version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}
    volumes:
      - ./frontend:/app
    ports:
      - "8000:80"
